export const searchData = [
  { id: 1, name: "Jane Doe", title: "Fo sanfai" },
  { id: 2, name: "Charlie Brown", title: "zidane" },
  { id: 3, name: "Alice Taylor", title: "Fo sanfai" },
  { id: 4, name: "Bob Smith", title: "Fo sanfai" },
  { id: 5, name: "John Johnson", title: "Fo sanfai" },
  { id: 6, name: "Jane Doe", title: "Fo sanfai" },
  { id: 7, name: "Alice Taylor", title: "Fo sanfai" },
  { id: 8, name: "Charlie Brown", title: "Fo sanfai" },
  { id: 9, name: "Bob Smith", title: "Fo sanfai" },
  { id: 10, name: "John Johnson", title: "Fo sanfai" },
  { id: 11, name: "Jane Doe", title: "Fo sanfai" },
  { id: 12, name: "Charlie Brown", title: "Fo sanfai" },
  { id: 13, name: "Alice Taylor", title: "Fo sanfai" },
  { id: 14, name: "Bob Smith", title: "Fo sanfai" },
  { id: 15, name: "John Johnson", title: "Fo sanfai" },
  { id: 16, name: "Jane Doe", title: "Fo sanfai" },
  { id: 17, name: "Alice Taylor", title: "Fo sanfai" },
  { id: 18, name: "Charlie Brown", title: "Fo sanfai" },
  { id: 19, name: "Bob Smith", title: "Fo sanfai" },
  { id: 20, name: "John Johnson", title: "Fo sanfai" },
  { id: 21, name: "Jane Doe", title: "Fo sanfai" },
  { id: 22, name: "Charlie Brown", title: "Fo sanfai" },
  { id: 23, name: "Alice Taylor", title: "Fo sanfai" },
  { id: 24, name: "Bob Smith", title: "Fo sanfai" },
  { id: 25, name: "John Johnson", title: "Fo sanfai" },
  { id: 26, name: "Jane Doe", title: "Fo sanfai" },
  { id: 27, name: "Alice Taylor", title: "Fo sanfai" },
  { id: 28, name: "Charlie Brown", title: "Fo sanfai" },
  { id: 29, name: "Bob Smith", title: "Fo sanfai" },
  { id: 30, name: "John Johnson", title: "Fo sanfai" },
  { id: 31, name: "Kaiwale crime", title: "ca marche" },
  { id: 32, name: "Ca me fais", title: "85 000" },
];
